blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/gr3enarr0w/star-wars-rpg-character-manager/blob/main/README.md
    about: Check the README and project documentation for setup and usage guides
  - name: 🔒 Security Issues
    url: https://github.com/gr3enarr0w/star-wars-rpg-character-manager/issues/new?template=bug_report.yml&labels=security,critical
    about: Report security vulnerabilities as bug reports with security label