name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - High (Essential for workflow)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the application would this feature affect?
      options:
        - Character Management
        - Campaign Management
        - User Interface/UX
        - Authentication/Security
        - API/Integration
        - Mobile Support
        - Performance
        - Admin Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Which type of user would primarily benefit from this feature?
      options:
        - Players
        - Game Masters
        - Administrators
        - All Users
        - Developers/API Users
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added
      placeholder: Provide a clear and detailed description of the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case/User Story
      description: Describe how you or others would use this feature
      placeholder: |
        As a [user type], I want to [action] so that [benefit/outcome].
        
        Example scenarios where this feature would be used...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your ideal implementation of this feature...

  - type: textarea
    id: ui-mockup
    attributes:
      label: UI/UX Mockup or Description
      description: If this affects the user interface, describe or sketch how it might look
      placeholder: Describe the user interface changes or attach mockups...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific requirements should this feature meet?
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there alternative ways to solve this problem?
      placeholder: Describe alternative approaches you've considered...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature might be to implement?
      options:
        - Simple (Minor UI changes, basic functionality)
        - Medium (New components, moderate backend changes)
        - Complex (Major architectural changes, extensive testing needed)
        - Not Sure

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes to existing functionality?
      options:
        - No breaking changes expected
        - Minor breaking changes
        - Significant breaking changes
        - Not sure

  - type: textarea
    id: related-features
    attributes:
      label: Related Features/Issues
      description: Are there existing features or issues this relates to?
      placeholder: |
        - Related to issue #123
        - Builds on feature XYZ
        - Conflicts with issue #456

  - type: textarea
    id: business-value
    attributes:
      label: Business Value/Impact
      description: What would be the positive impact of implementing this feature?
      placeholder: |
        - Improves user experience by...
        - Reduces time spent on...
        - Enables new use cases like...
        - Addresses common user complaints about...

  - type: input
    id: target-version
    attributes:
      label: Target Version
      description: Which version would you like to see this feature in?
      placeholder: e.g., v1.1.0, v2.0.0, or "any future version"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references
      placeholder: |
        - Similar features in other applications
        - Links to relevant documentation
        - Community discussion links
        - Any other relevant information

  - type: checkboxes
    id: research
    attributes:
      label: Research Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have checked the project roadmap for similar planned features
          required: true
        - label: I have considered the impact on existing users
          required: true
        - label: I understand this is a public repository and my suggestion will be visible
          required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be interested in implementing this feature myself
          required: false
        - label: I would be willing to help with testing
          required: false
        - label: I could provide additional requirements or feedback
          required: false
        - label: I would be willing to help with documentation
          required: false